name: Build and Deploy
permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.2

      - name: Install dependencies and build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          ACCESS_TOKEN: ${{ secrets.GITHUBTOKEN }}