name: Test
permissions:
  contents: write

on: 
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.2

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Test
        run: pnpm run test